import { LOCKUP, MARK, WORDMARK } from './logoData';

// Equigift mark: a pie chart (the company) with one slice lifted out,
// ribbon-wrapped and topped with a bow (the share you give).
// Geometry is generated by scripts/build-logo.mjs.
export function MarkPaths({ pie, slice }: { pie: string; slice: string }) {
  return (
    <>
      <path d={MARK.pie} fill={pie} />
      {MARK.slice.map((d) => (
        <path key={d} d={d} fill={slice} />
      ))}
      <g fill="none" stroke={slice} strokeWidth={MARK.bowWidth} strokeLinejoin="round">
        {MARK.bow.map((d) => (
          <path key={d} d={d} />
        ))}
      </g>
    </>
  );
}

export function LogoMark({ className, dark = false }: { className?: string; dark?: boolean }) {
  return (
    <svg className={className} viewBox="2 -0.5 60 66" role="img" aria-label="Equigift">
      <MarkPaths pie={dark ? 'var(--invert-fg1)' : 'var(--fg1)'} slice="var(--accent)" />
    </svg>
  );
}

export function Wordmark({ className, color = 'currentColor' }: { className?: string; color?: string }) {
  return (
    <svg className={className} viewBox={`0 0 ${WORDMARK.w} ${WORDMARK.h}`} aria-hidden="true" focusable="false">
      <path d={WORDMARK.d} fill={color} />
    </svg>
  );
}

/** Mark + wordmark as one SVG. */
export function Lockup({ dark = false }: { dark?: boolean }) {
  const ink = dark ? 'var(--invert-fg1)' : 'var(--fg1)';
  return (
    <svg className="lockup" viewBox={LOCKUP.viewBox} role="img" aria-label="Equigift">
      <MarkPaths pie={ink} slice="var(--accent)" />
      <path d={LOCKUP.word} fill={ink} />
    </svg>
  );
}
